### ISSUE TITLE
0.91.8 no longer supports Django 1.6 due to deconstructible

### ISSUE THREAD

**Issue by Rizziepit** [Starou/django-thumborstorage#12]
The `deconstructible` import [here](https://github.com/Starou/django-thumborstorage/blob/master/django_thumborstorage/storages.py#L11) raises `ImportError` in Django 1.6 since migrations were only introduced in Django 1.7. Can I open a PR to fix it?

**Comment by Starou** [comment]
There is already a [PR](https://github.com/lCharlie123l/django-thumborstorage/commit/97e8132f682d9c100d853ceba2fd09c6369f96e2) with a commit for this issue.
But as requested this should be a unique PR.

By the way, I think an implementation like [django-storage](https://github.com/jschneier/django-storages/blob/master/storages/compat.py) is cleaner.

Can you open a PR please?
