### ISSUE TITLE
response.status_code isn't checked when saving image into thumbor

### ISSUE THREAD

**Issue by mojeto** [Starou/django-thumborstorage#16]
Hi, 
Response status code isn't checked after saving image file into thumbor server. [ThumborStorageFile.write](https://github.com/Starou/django-thumborstorage/blob/master/django_thumborstorage/storages.py#L45)
Thumbor server can respond with several HTTP statuses [thumbor doc](https://github.com/thumbor/thumbor/wiki/Posting,-putting-and-deleting#http-status-code) 

- 201 Created (success)
- 409 Conflict (image already exists)
- 412 Precondition Failed (image is too small or the file is not an image)
- 415 Unsupported Media Type (not documented, but can happen) 

If upload wasn't successful code fails on exception
`
  File "/usr/lib/python2.7/site-packages/django_thumborstorage/storages.py", line 102, in _save
    f.write(content=content)
  File "/usr/lib/python2.7/site-packages/django_thumborstorage/storages.py", line 46, in write
    self._location = unquote(response.headers["location"])
  File "/usr/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
`

Can we check response status and raise proper exception based on it?
e.g. **415 Unsupported Media Type** can be ValidationError maybe

**Comment by Starou** [comment]
Hi,

You are correct. However, the Wiki page your are refering to is not up-to-date (last update in 2012). It does not document the 415 code and I can't see when 409 should be returned since you can POST the same image twice, it is just another entry in Thumbor.
I can't have Thumbor to return a 412 too. When I upload a PDF or a XML file, it always returns 415.

https://github.com/thumbor/thumbor/blob/d8b7e5877ed7ad26cee511e24c33ecd9394e0711/docs/how_to_upload_images.rst

Just pushed a branch : Can you test it please?

**Comment by mojeto** [comment]
Thank you, 
it works, but in log it says "No exception message supplied" so it's hard to see why it went wrong.
Can you past through the error message into Exception parent please? e.g.

`
class ThumborPostException(DjangoThumborStorageException):
    _error = None

    def __init__(self, response):
        self._error = "%d - %s" % (response.status_code, response.reason)
        super(ThumborPostException, self).__init__(self._error)

    def __repr__(self):
        print(self._error)
`

**Comment by Starou** [comment]
That was `__str__()` instead of `__repr__`. Fix has been pushed.

```
======================================================================
ERROR: test_write_image_too_small (regressiontests.storages.ThumborStorageFileTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sguerra/Dropbox (Slashdev S.A.R.L.)/Projets/Slashdev/django-thumborstorage/repos/starou/django-thumborstorage/tests/regressiontests/storages.py", line 151, in test_write_image_too_small
    thumbor_file.write(content=content)
  File "../django_thumborstorage/storages.py", line 47, in write
    raise exceptions.ThumborPostException(response)
ThumborPostException: '412 - Image too small'
```



Thanks for the feedback.
Feel free to open a PR next time you find a bug and nail down the problem, it is even better!

Cheers.

**Comment by mojeto** [comment]
perfect, thanks
Next time I will do a PR.
Cheers,
