### ISSUE TITLE
ThumborStorageFile.close causes a new image download from thumbor server

### ISSUE THREAD

**Issue by mojeto** [Starou/django-thumborstorage#18]
Hi,
I found this issue when I optimised our production setup.
Configuration we use is django -> ThumborStorageFile -> Thumbor server -> S3 bucket (as image storage)

```
# django model
class Image(models.Model):
    checksum = models.CharField(max_length=40, unique=True, db_index=True)
    image = models.ImageField(
        upload_to='image/',
        storage=ThumborStorage(),
        height_field='height',
        width_field='width'
    )
    height = models.IntegerField(blank=True, null=True, db_index=True)
    width = models.IntegerField(blank=True, null=True, db_index=True)
``` 

Upload image workflow (save method):

1. Image is uploaded to thumbor server in `ThumborStorageFile.write` method
2. Image is downloaded from thumbor server because of [`ThumborStorageFile. _get_image_dimensions`](https://github.com/django/django/blob/master/django/core/files/images.py)
3. after getting image dimensions, the file is closed - here is a bug (more follow in code comments) 
```
class ThumborStorageFile(ImageFile):

    file = property(_get_file, _set_file)

    def close(self):
        self._file = None  # pointer to file is removed
        super(ThumborStorageFile, self).close()  
        # parent method touch file property which will cause a new file download.

    # parent method from class File 
    def close(self):
         self.file.close()    
         # self.file goes to self._get_file which reads from self._file 
         # because self._file == None  _get_file starts a new download from thumbor server
         # the only method called on fresh downloaded image is .close()  :-(
 ```
[source of django File](https://github.com/django/django/blob/master/django/core/files/base.py#L139)

**Comment by Starou** [comment]
Hi @mojeto.

Thanks for the thorough explanation and the PR. I'll run some tests locally before merging.
