### ISSUE TITLE
Missing version 1.9.12

### ISSUE THREAD

**Issue by RealOrangeOne** [Starou/django-thumborstorage#25]
Some projects I work on are currently pinned to version `1.9.12`, which appears to have vanished from PyPi, is this intentional? Is there a reason for this?

I've got a version of `1.9.12` installed locally, but when trying to install from TravisCI, I get this message:

```
Could not find a version that satisfies the requirement django-thumborstorage==1.9.12 (from -r requirements.txt (line 14)) (from versions: 0.91.1, 0.91.2, 0.91.3, 0.91.4, 0.91.5, 0.91.6, 0.91.7, 0.91.8, 0.92.0, 1.11.1)
No matching distribution found for django-thumborstorage==1.9.12 (from -r requirements.txt (line 14))
```

This version number looks very similar to `0.91.2`, was there just a version numbering change?

**Comment by Starou** [comment]
Please reopen this issue if you have any trouble.
